// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flashCardBackend.Services.Context;

#nullable disable

namespace Template.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("flashCardBackend.Models.CsharpCardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodeAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsharpAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsharpQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CsharpFlashCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeAnswer = "",
                            CsharpAnswer = "WriteLine prints the output on a new line each time",
                            CsharpQuestion = "What Is A Writeline"
                        },
                        new
                        {
                            Id = 2,
                            CodeAnswer = "",
                            CsharpAnswer = "Write prints on the same line",
                            CsharpQuestion = "What Is A Write"
                        },
                        new
                        {
                            Id = 3,
                            CodeAnswer = "",
                            CsharpAnswer = "Any text between // and the end of the line is ignored by C#",
                            CsharpQuestion = "What Does // Do"
                        },
                        new
                        {
                            Id = 4,
                            CodeAnswer = "",
                            CsharpAnswer = "The throw statement allows you to create a custom error",
                            CsharpQuestion = "What Does Throw Do"
                        },
                        new
                        {
                            Id = 5,
                            CodeAnswer = "",
                            CsharpAnswer = "The finally statement lets you execute code, after try...catch, regardless of the result",
                            CsharpQuestion = "What Does Finally D0"
                        },
                        new
                        {
                            Id = 6,
                            CodeAnswer = "",
                            CsharpAnswer = "you should always use them together,",
                            CsharpQuestion = "Should You Use A Try And Catch"
                        },
                        new
                        {
                            Id = 7,
                            CodeAnswer = "",
                            CsharpAnswer = "A catch statement allows you to define a block of code to be executed, if an error occurs in the try block",
                            CsharpQuestion = "What Does A Catch Statement Do"
                        },
                        new
                        {
                            Id = 8,
                            CodeAnswer = "",
                            CsharpAnswer = "A try statement allows you to define a block of code to be tested for errors while it is being executed",
                            CsharpQuestion = "What Does A Try Statement Do"
                        },
                        new
                        {
                            Id = 9,
                            CodeAnswer = "",
                            CsharpAnswer = "yes , you can also have an enum inside a class",
                            CsharpQuestion = "Can Enums Be Used In Classes"
                        },
                        new
                        {
                            Id = 10,
                            CodeAnswer = "",
                            CsharpAnswer = "To create an enum, use the enum keyword (instead of class or interface)",
                            CsharpQuestion = "How Do You Create A Enum"
                        },
                        new
                        {
                            Id = 11,
                            CodeAnswer = "",
                            CsharpAnswer = "you use enums when you have values that you know aren't going to change",
                            CsharpQuestion = "Why Would You Use Enum"
                        },
                        new
                        {
                            Id = 12,
                            CodeAnswer = "",
                            CsharpAnswer = "An enum is a special \"class\" that represents a group of constants (unchangeable/read-only variables)",
                            CsharpQuestion = "What Is A Enum"
                        },
                        new
                        {
                            Id = 13,
                            CodeAnswer = "",
                            CsharpAnswer = "yes, to implement multiple interfaces, separate them with a comma",
                            CsharpQuestion = "Can You Have Multiple Interfaces"
                        },
                        new
                        {
                            Id = 14,
                            CodeAnswer = "",
                            CsharpAnswer = "C# does not support \"multiple inheritance\" (a class can only inherit from one base class). However, it can be achieved with interfaces, because the class can implement multiple interfaces",
                            CsharpQuestion = "Why Use A Interface Over Abstract"
                        },
                        new
                        {
                            Id = 15,
                            CodeAnswer = "",
                            CsharpAnswer = "interface",
                            CsharpQuestion = "What Keyword Makes A Interface"
                        },
                        new
                        {
                            Id = 16,
                            CodeAnswer = "",
                            CsharpAnswer = "An interface is a completely \"abstract class\", which can only contain abstract methods and properties",
                            CsharpQuestion = "What Is A Interface"
                        },
                        new
                        {
                            Id = 17,
                            CodeAnswer = "",
                            CsharpAnswer = "To achieve security - hide certain details and only show the important details of an object",
                            CsharpQuestion = "Why Would We Use Abstract"
                        },
                        new
                        {
                            Id = 18,
                            CodeAnswer = "",
                            CsharpAnswer = "abstract",
                            CsharpQuestion = "What Keyword Makes Data Abstraction"
                        },
                        new
                        {
                            Id = 19,
                            CodeAnswer = "",
                            CsharpAnswer = "Data abstraction is the process of hiding certain details and showing only essential information to the user",
                            CsharpQuestion = "What Is Data Abstraction In C#"
                        },
                        new
                        {
                            Id = 20,
                            CodeAnswer = "",
                            CsharpAnswer = "it is used If you don't want other classes to inherit from a class",
                            CsharpQuestion = "What Is A Sealed Used For"
                        },
                        new
                        {
                            Id = 21,
                            CodeAnswer = "",
                            CsharpAnswer = "A \":\" is used",
                            CsharpQuestion = "To Inherit From A Class What Symbol Is Used"
                        },
                        new
                        {
                            Id = 22,
                            CodeAnswer = "",
                            CsharpAnswer = "Parent Class",
                            CsharpQuestion = "What Is Another Name For A Base Class"
                        },
                        new
                        {
                            Id = 23,
                            CodeAnswer = "",
                            CsharpAnswer = "Child Class",
                            CsharpQuestion = "What Is Another Name For A Derived Class"
                        },
                        new
                        {
                            Id = 24,
                            CodeAnswer = "",
                            CsharpAnswer = "the class being inherited from",
                            CsharpQuestion = "What Is A Base Class"
                        },
                        new
                        {
                            Id = 25,
                            CodeAnswer = "",
                            CsharpAnswer = "it is the class that inherits from another class",
                            CsharpQuestion = "What Is A Derived Class"
                        },
                        new
                        {
                            Id = 26,
                            CodeAnswer = "",
                            CsharpAnswer = " It is useful for code reusability: reuse fields and methods of an existing class when you create a new class",
                            CsharpQuestion = "Why Do We Inheritance Code In C#"
                        },
                        new
                        {
                            Id = 27,
                            CodeAnswer = "",
                            CsharpAnswer = "you have to write get; and set; inside the property",
                            CsharpQuestion = "How Do You Short Hand A Property"
                        },
                        new
                        {
                            Id = 28,
                            CodeAnswer = "",
                            CsharpAnswer = "The set method assigns a value to the variable",
                            CsharpQuestion = "What Does A Set Method Do"
                        },
                        new
                        {
                            Id = 29,
                            CodeAnswer = "",
                            CsharpAnswer = "The get method returns the value of the variable",
                            CsharpQuestion = "What Does A Get Method Do"
                        },
                        new
                        {
                            Id = 30,
                            CodeAnswer = "",
                            CsharpAnswer = "A property is like a combination of a variable and a method, and it has two methods: a get and a set method",
                            CsharpQuestion = "What Is A Property"
                        },
                        new
                        {
                            Id = 31,
                            CodeAnswer = "",
                            CsharpAnswer = "makes the code only accessible within its own assembly, but not from another assembly",
                            CsharpQuestion = "What Does Internal Do"
                        },
                        new
                        {
                            Id = 32,
                            CodeAnswer = "",
                            CsharpAnswer = "makes the code accessible within the same class, or in a class that is inherited from that class",
                            CsharpQuestion = "What Does Protected Do"
                        },
                        new
                        {
                            Id = 33,
                            CodeAnswer = "",
                            CsharpAnswer = "makes the code only accessible within the same class",
                            CsharpQuestion = "What Does Private Do"
                        },
                        new
                        {
                            Id = 34,
                            CodeAnswer = "",
                            CsharpAnswer = "makes the code accessible for all classes",
                            CsharpQuestion = "What Does Public Do"
                        },
                        new
                        {
                            Id = 35,
                            CodeAnswer = "",
                            CsharpAnswer = "protected internal , private protected",
                            CsharpQuestion = "What Are The Two Access Modifiers That Have Combinations"
                        },
                        new
                        {
                            Id = 36,
                            CodeAnswer = "",
                            CsharpAnswer = "public , private , protected , internal",
                            CsharpQuestion = "What Access Modifiers Are There"
                        },
                        new
                        {
                            Id = 37,
                            CodeAnswer = "",
                            CsharpAnswer = "it is used to set the access level/visibility for classes, fields, methods and properties",
                            CsharpQuestion = "What Are Access Modifiers Used For"
                        },
                        new
                        {
                            Id = 38,
                            CodeAnswer = "",
                            CsharpAnswer = "constructors save time! , they help reducing the amount of code",
                            CsharpQuestion = "Why Would You Use A Constructor"
                        },
                        new
                        {
                            Id = 39,
                            CodeAnswer = "",
                            CsharpAnswer = "Constructors can also take parameters, which is used to initialize fields",
                            CsharpQuestion = "Can  Constructor Take Parameters"
                        },
                        new
                        {
                            Id = 40,
                            CodeAnswer = "",
                            CsharpAnswer = "constructor name must match the class name",
                            CsharpQuestion = "Should The Constructor Have The Same Name As The Class"
                        },
                        new
                        {
                            Id = 41,
                            CodeAnswer = "",
                            CsharpAnswer = "A constructor is a special method that is used to initialize objects",
                            CsharpQuestion = "What Is A Constructor"
                        },
                        new
                        {
                            Id = 42,
                            CodeAnswer = "",
                            CsharpAnswer = "Fields and methods inside classes are often referred to as \"Class Members\"",
                            CsharpQuestion = "What Are Class Members"
                        },
                        new
                        {
                            Id = 43,
                            CodeAnswer = "",
                            CsharpAnswer = "Yes, You can create multiple objects of one class",
                            CsharpQuestion = "Can You Use Multiple Objects In One Class"
                        },
                        new
                        {
                            Id = 44,
                            CodeAnswer = "",
                            CsharpAnswer = "To create an object of Car, specify the class name, followed by the object name, and use the keyword new",
                            CsharpQuestion = "How Do You Make A Object"
                        },
                        new
                        {
                            Id = 45,
                            CodeAnswer = "",
                            CsharpAnswer = "you make a class using the keyword class",
                            CsharpQuestion = "How Do You Make A Class"
                        },
                        new
                        {
                            Id = 46,
                            CodeAnswer = "",
                            CsharpAnswer = "OOP stands for Object-Oriented Programming",
                            CsharpQuestion = "What Does Oop Stand For"
                        },
                        new
                        {
                            Id = 47,
                            CodeAnswer = "",
                            CsharpAnswer = "You can add as many parameters as you want, just separate them with a comma",
                            CsharpQuestion = "How Many Parameters Can You Have In A Method"
                        },
                        new
                        {
                            Id = 48,
                            CodeAnswer = "",
                            CsharpAnswer = "Arguments",
                            CsharpQuestion = "What Are The Vaules You Pass Into A Parameter Called"
                        },
                        new
                        {
                            Id = 49,
                            CodeAnswer = "",
                            CsharpAnswer = "Information that can be passed to methods as parameter. Parameters act as variables inside the method.",
                            CsharpQuestion = "What Are Method Parameters"
                        },
                        new
                        {
                            Id = 50,
                            CodeAnswer = "",
                            CsharpAnswer = " write the method's name followed by two parentheses () and a semicolon",
                            CsharpQuestion = "How Do You Call A Method"
                        },
                        new
                        {
                            Id = 51,
                            CodeAnswer = "",
                            CsharpAnswer = "A method is made with the name of the method, followed by parentheses ()",
                            CsharpQuestion = "How Do You Make A Method"
                        },
                        new
                        {
                            Id = 52,
                            CodeAnswer = "",
                            CsharpAnswer = "A method is a block of code which only runs when it is called",
                            CsharpQuestion = "What Is A Method"
                        },
                        new
                        {
                            Id = 53,
                            CodeAnswer = "",
                            CsharpAnswer = "Sort will sort an array alphabetically or in an ascending order",
                            CsharpQuestion = "What Does Sort() Do To A Array"
                        },
                        new
                        {
                            Id = 54,
                            CodeAnswer = "",
                            CsharpAnswer = "You can loop through the array elements with the for loop, and use the Length property to specify how many times the loop should run",
                            CsharpQuestion = "How Do You Loop Through An Array"
                        },
                        new
                        {
                            Id = 55,
                            CodeAnswer = "",
                            CsharpAnswer = "finds out how many elements an array has",
                            CsharpQuestion = "What Does .Length Do To A Array"
                        },
                        new
                        {
                            Id = 56,
                            CodeAnswer = "",
                            CsharpAnswer = "To change the value of a specific element, refer to the index number and then set the vaule to other variable",
                            CsharpQuestion = "How Do You Change An Array Element"
                        },
                        new
                        {
                            Id = 57,
                            CodeAnswer = "",
                            CsharpAnswer = "You access an array element by referring to the index number",
                            CsharpQuestion = "How Do You Access The Elements Of An Array"
                        },
                        new
                        {
                            Id = 58,
                            CodeAnswer = "",
                            CsharpAnswer = "Arrays are used to store multiple values in a single variable, instead of declaring separate variables for each value",
                            CsharpQuestion = "What Are Arrays Used For"
                        },
                        new
                        {
                            Id = 59,
                            CodeAnswer = "",
                            CsharpAnswer = "continue statement breaks one iteration (in the loop), if a specified condition occurs, and continues with the next iteration in the loop",
                            CsharpQuestion = "What Does Continue Do In A Loop"
                        },
                        new
                        {
                            Id = 60,
                            CodeAnswer = "",
                            CsharpAnswer = "break statement can be used to jump out of a loop",
                            CsharpQuestion = "What Does A Break Do In A Loop"
                        },
                        new
                        {
                            Id = 61,
                            CodeAnswer = "",
                            CsharpAnswer = "foreach loop is used exclusively to loop through elements in an array",
                            CsharpQuestion = "What Is A Foreach Loop For"
                        },
                        new
                        {
                            Id = 62,
                            CodeAnswer = "",
                            CsharpAnswer = "For Loop will loop through a specific number of times",
                            CsharpQuestion = "What Does A For Loop Do"
                        },
                        new
                        {
                            Id = 63,
                            CodeAnswer = "",
                            CsharpAnswer = "Do/While loop will execute the code block once, before checking if the condition is true, then it will repeat the loop as long as the condition is true",
                            CsharpQuestion = "What Does A Do/While Loop Do"
                        },
                        new
                        {
                            Id = 64,
                            CodeAnswer = "",
                            CsharpAnswer = "default specifies some code to run if there is no case match",
                            CsharpQuestion = "What Does Default Do In A Switch Statement "
                        },
                        new
                        {
                            Id = 65,
                            CodeAnswer = "",
                            CsharpAnswer = "break when a match is found will stop the execution of more code and case testing inside the block",
                            CsharpQuestion = "What Does Break Do In A Switch Statement"
                        },
                        new
                        {
                            Id = 66,
                            CodeAnswer = "",
                            CsharpAnswer = "A switch statement is used to select one of many code blocks to be executed",
                            CsharpQuestion = "What Does A  Switch Statement Do"
                        },
                        new
                        {
                            Id = 67,
                            CodeAnswer = "",
                            CsharpAnswer = " you can use it to replace multiple lines of code with a single line. It is often used to replace simple if else statements",
                            CsharpQuestion = "Why Would You Use Ternary Operators"
                        },
                        new
                        {
                            Id = 68,
                            CodeAnswer = "",
                            CsharpAnswer = "\"?\" is the if statement ternary operator and : is the else statement ternary operator",
                            CsharpQuestion = "What Do If Else Ternary Operators Look Like"
                        },
                        new
                        {
                            Id = 69,
                            CodeAnswer = "",
                            CsharpAnswer = "you use a else if statement to specify a new condition if the first condition is False",
                            CsharpQuestion = "What Does A Else If Statement Do"
                        },
                        new
                        {
                            Id = 70,
                            CodeAnswer = "",
                            CsharpAnswer = "you use a else statement to specify a block of code to be executed if the condition is False",
                            CsharpQuestion = "What Does A Else Statement Do"
                        },
                        new
                        {
                            Id = 71,
                            CodeAnswer = "",
                            CsharpAnswer = "you use a if statement to specify a block of C# code to be executed if a condition is True",
                            CsharpQuestion = "What Does A If Statement Do"
                        },
                        new
                        {
                            Id = 72,
                            CodeAnswer = "",
                            CsharpAnswer = "if , if else , else , switch",
                            CsharpQuestion = "What Are The If Statements And Conditions Called"
                        },
                        new
                        {
                            Id = 73,
                            CodeAnswer = "",
                            CsharpAnswer = "Boolean Expression uses a comparison operator, such as the greater than (>) operator to find out if an expression (or a variable) is true",
                            CsharpQuestion = "What Does A Boolean Expression Do"
                        },
                        new
                        {
                            Id = 74,
                            CodeAnswer = "",
                            CsharpAnswer = "you declare it has bool then vaule name",
                            CsharpQuestion = "How Do You Make A Vaule Type Boolean"
                        },
                        new
                        {
                            Id = 75,
                            CodeAnswer = "",
                            CsharpAnswer = "the vaules are true , false",
                            CsharpQuestion = "What Are The Two Vaules A Boolean Has"
                        },
                        new
                        {
                            Id = 76,
                            CodeAnswer = "",
                            CsharpAnswer = "A boolean has two vaules",
                            CsharpQuestion = "How Many Vaules Does A Boolean Have"
                        },
                        new
                        {
                            Id = 77,
                            CodeAnswer = "",
                            CsharpAnswer = " using \"+\" and .Concat() or String Interpolation",
                            CsharpQuestion = "What Are The Three Ways To Do String Concatenation"
                        },
                        new
                        {
                            Id = 78,
                            CodeAnswer = "",
                            CsharpAnswer = "String Concatenation is when you combine to strings together",
                            CsharpQuestion = "What Is String Concatenation"
                        },
                        new
                        {
                            Id = 79,
                            CodeAnswer = "",
                            CsharpAnswer = "it find the length of a string or array",
                            CsharpQuestion = "What Does .Length Do"
                        },
                        new
                        {
                            Id = 80,
                            CodeAnswer = "",
                            CsharpAnswer = "it makes all letters in a string lower case",
                            CsharpQuestion = "What Does .Tolower Do"
                        },
                        new
                        {
                            Id = 81,
                            CodeAnswer = "",
                            CsharpAnswer = "it makes all letters in a string upper case",
                            CsharpQuestion = "What Does .Toupper Do"
                        },
                        new
                        {
                            Id = 82,
                            CodeAnswer = "",
                            CsharpAnswer = ".Length ,  .ToUpper() , ToLower()",
                            CsharpQuestion = "What Methods Can You Use On Type String"
                        },
                        new
                        {
                            Id = 83,
                            CodeAnswer = "",
                            CsharpAnswer = "Math.Round rounds a number to the nearest whole number",
                            CsharpQuestion = "What Does Math.Round Do"
                        },
                        new
                        {
                            Id = 84,
                            CodeAnswer = "",
                            CsharpAnswer = "Math.Abs returns the absolute (positive) value of x",
                            CsharpQuestion = "What Does Math.Abs Do"
                        },
                        new
                        {
                            Id = 85,
                            CodeAnswer = "",
                            CsharpAnswer = "Math.Sqrt returns the square root of x",
                            CsharpQuestion = "What Does Math.Sqrt Do"
                        },
                        new
                        {
                            Id = 86,
                            CodeAnswer = "",
                            CsharpAnswer = "Math.min can be used to find the lowest value of of x and y",
                            CsharpQuestion = "What Does Math.Min Do"
                        },
                        new
                        {
                            Id = 87,
                            CodeAnswer = "",
                            CsharpAnswer = "Math.Max can be used to find the highest value of x and y",
                            CsharpQuestion = "What Does Math.Max Do"
                        },
                        new
                        {
                            Id = 88,
                            CodeAnswer = "",
                            CsharpAnswer = "Max , Min , Sqrt , Abs , Round",
                            CsharpQuestion = "What Methods Does Math Have In C#"
                        },
                        new
                        {
                            Id = 89,
                            CodeAnswer = "",
                            CsharpAnswer = "Reverse the result, returns false if the result is true",
                            CsharpQuestion = "What Does The \"!\" Operator Do"
                        },
                        new
                        {
                            Id = 90,
                            CodeAnswer = "",
                            CsharpAnswer = "Returns true if one of the statements is true",
                            CsharpQuestion = "What Does The \"||\" Operator Do"
                        },
                        new
                        {
                            Id = 91,
                            CodeAnswer = "",
                            CsharpAnswer = "Returns true if both statements are true",
                            CsharpQuestion = "What Does The \"&&\" Operator Do"
                        },
                        new
                        {
                            Id = 92,
                            CodeAnswer = "",
                            CsharpAnswer = "Logical operators are used to determine the logic between variables or values",
                            CsharpQuestion = "What Do Logical Operators Do"
                        },
                        new
                        {
                            Id = 93,
                            CodeAnswer = "",
                            CsharpAnswer = "\"|| , && , ! \"",
                            CsharpQuestion = "What Do Logical Operators Look Like"
                        },
                        new
                        {
                            Id = 94,
                            CodeAnswer = "",
                            CsharpAnswer = "checks if the vaule is less than or equal to the other value ",
                            CsharpQuestion = "What Does The \"<=\" Operator Do"
                        },
                        new
                        {
                            Id = 95,
                            CodeAnswer = "",
                            CsharpAnswer = "checks if the vaule is greater than or equal to the other value ",
                            CsharpQuestion = "What Does The \">=\" Operator Do"
                        },
                        new
                        {
                            Id = 96,
                            CodeAnswer = "",
                            CsharpAnswer = "checks if the vaule is less than the other vaule",
                            CsharpQuestion = "What Does The \"<\" Operator Do"
                        },
                        new
                        {
                            Id = 97,
                            CodeAnswer = "",
                            CsharpAnswer = "checks if the vaule is greater than the other vaule",
                            CsharpQuestion = "What Does The \">\" Operator Do"
                        },
                        new
                        {
                            Id = 98,
                            CodeAnswer = "",
                            CsharpAnswer = "checks if vaules are not equal to each other",
                            CsharpQuestion = "What Does The \"!=\" Operator Do"
                        },
                        new
                        {
                            Id = 99,
                            CodeAnswer = "",
                            CsharpAnswer = "checks if both vaules are equal to each other",
                            CsharpQuestion = "What Does The \"==\" Operator Do"
                        },
                        new
                        {
                            Id = 100,
                            CodeAnswer = "",
                            CsharpAnswer = "Comparison operators are used to compare two values",
                            CsharpQuestion = "What Do Comparison Operators Do"
                        },
                        new
                        {
                            Id = 101,
                            CodeAnswer = "",
                            CsharpAnswer = "\"== , != , > , < , >= , <=\"",
                            CsharpQuestion = "What Do Comparison Operators Look Like"
                        },
                        new
                        {
                            Id = 102,
                            CodeAnswer = "",
                            CsharpAnswer = "\"=\"",
                            CsharpQuestion = "What Does The Default  Assignment Operator Look Like"
                        },
                        new
                        {
                            Id = 103,
                            CodeAnswer = "",
                            CsharpAnswer = "Assignment operators are used to assign values to variables.",
                            CsharpQuestion = "What Do Assignment Operators Do"
                        },
                        new
                        {
                            Id = 104,
                            CodeAnswer = "",
                            CsharpAnswer = "Decreases the value of a variable by 1",
                            CsharpQuestion = "What Does \"--\" Operator Do?"
                        },
                        new
                        {
                            Id = 105,
                            CodeAnswer = "",
                            CsharpAnswer = "Increases the value of a variable by 1",
                            CsharpQuestion = "What Does \"++\" Operator Do?"
                        },
                        new
                        {
                            Id = 106,
                            CodeAnswer = "",
                            CsharpAnswer = "Multiplies two values",
                            CsharpQuestion = "What Does * Operator Do?"
                        },
                        new
                        {
                            Id = 107,
                            CodeAnswer = "",
                            CsharpAnswer = "Returns the division remainder",
                            CsharpQuestion = "What Does \"%\" Operator Do?"
                        },
                        new
                        {
                            Id = 108,
                            CodeAnswer = "",
                            CsharpAnswer = "Divides one value by another",
                            CsharpQuestion = "What Does \"/\" Operator Do?"
                        },
                        new
                        {
                            Id = 109,
                            CodeAnswer = "",
                            CsharpAnswer = "Subtracts one value from another",
                            CsharpQuestion = "What Does \"-\" Operator Do?"
                        },
                        new
                        {
                            Id = 110,
                            CodeAnswer = "",
                            CsharpAnswer = "Adds together two values",
                            CsharpQuestion = "What Does \"+\" Operator Do?"
                        },
                        new
                        {
                            Id = 111,
                            CodeAnswer = "",
                            CsharpAnswer = "- + = * / % ++ --",
                            CsharpQuestion = "What Do Arithmetic Operators Look Like"
                        },
                        new
                        {
                            Id = 112,
                            CodeAnswer = "",
                            CsharpAnswer = "it outputs values aka prints values",
                            CsharpQuestion = "What Does A Console.Writeline() Do"
                        },
                        new
                        {
                            Id = 113,
                            CodeAnswer = "",
                            CsharpAnswer = "it gets a user's input",
                            CsharpQuestion = "What Does A Console.Readline() Do"
                        },
                        new
                        {
                            Id = 114,
                            CodeAnswer = "",
                            CsharpAnswer = "Convert.ToBoolean, Convert.ToDouble, Convert.ToString, Convert.ToInt32 (int) and Convert.ToInt64 (long)",
                            CsharpQuestion = "What Are The Type Conversion Methods"
                        },
                        new
                        {
                            Id = 115,
                            CodeAnswer = "",
                            CsharpAnswer = "manually converting a larger number type to a smaller size number type",
                            CsharpQuestion = "What Does Explicit Casting"
                        },
                        new
                        {
                            Id = 116,
                            CodeAnswer = "",
                            CsharpAnswer = "automatically converting a smaller number type to a larger number type size",
                            CsharpQuestion = "What Does Implicit Casting Do"
                        },
                        new
                        {
                            Id = 117,
                            CodeAnswer = "",
                            CsharpAnswer = "float and double",
                            CsharpQuestion = "What Data Types Can Store Scientific Numbers"
                        },
                        new
                        {
                            Id = 118,
                            CodeAnswer = "",
                            CsharpAnswer = "float data type can store fractional numbers from 3.4e−038 to 3.4e+038. Note that you should end the value with an \"F\"",
                            CsharpQuestion = "What Is A Float"
                        },
                        new
                        {
                            Id = 119,
                            CodeAnswer = "",
                            CsharpAnswer = "These unique names are called identifiers",
                            CsharpQuestion = "What Is The Unique Names Of Variables Called?"
                        },
                        new
                        {
                            Id = 120,
                            CodeAnswer = "",
                            CsharpAnswer = "This is used when int is not large enough to store the value. Note that you should end the value with an \"L\"",
                            CsharpQuestion = "What Does Lond Do"
                        },
                        new
                        {
                            Id = 121,
                            CodeAnswer = "",
                            CsharpAnswer = "this will declare the variable as \"constant\", which means unchangeable and read-only",
                            CsharpQuestion = "What Does Const Do"
                        },
                        new
                        {
                            Id = 122,
                            CodeAnswer = "",
                            CsharpAnswer = "stores values with two states: true or false",
                            CsharpQuestion = "What Is A Bool"
                        },
                        new
                        {
                            Id = 123,
                            CodeAnswer = "",
                            CsharpAnswer = "stores text, such as \"Hello World\". String values are surrounded by double quotes",
                            CsharpQuestion = "What Is A String"
                        },
                        new
                        {
                            Id = 124,
                            CodeAnswer = "",
                            CsharpAnswer = "stores single characters, such as 'a' or 'B'. Char values are surrounded by single quotes",
                            CsharpQuestion = "What Is A Char"
                        },
                        new
                        {
                            Id = 125,
                            CodeAnswer = "",
                            CsharpAnswer = "A double stores floating point numbers that also have decimals",
                            CsharpQuestion = "What Is A Double"
                        },
                        new
                        {
                            Id = 126,
                            CodeAnswer = "",
                            CsharpAnswer = "A int stores a whole number",
                            CsharpQuestion = "What Is A Int"
                        });
                });

            modelBuilder.Entity("flashCardBackend.Models.HtmlCardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodeAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HtmlFlashCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeAnswer = "",
                            HtmlAnswer = "HTML stands for Hyper Text Markup Language",
                            HtmlQuestion = "What Does Html Stand For"
                        },
                        new
                        {
                            Id = 2,
                            CodeAnswer = "",
                            HtmlAnswer = "HTML element is defined by a start tag, some content, and an end tag",
                            HtmlQuestion = "What Is An Html Element"
                        },
                        new
                        {
                            Id = 3,
                            CodeAnswer = "",
                            HtmlAnswer = "The <!DOCTYPE html> declaration defines that this document is an HTML5 document",
                            HtmlQuestion = "What Does The <!Doctype Html> Tag Do"
                        },
                        new
                        {
                            Id = 4,
                            CodeAnswer = "",
                            HtmlAnswer = "The autoplay attribute starts the a audio file automatically",
                            HtmlQuestion = "What Does The Autoplay Attribute Do To A <Audio> Tag"
                        },
                        new
                        {
                            Id = 5,
                            CodeAnswer = "",
                            HtmlAnswer = "The HTML <audio> element is used to play an audio file on a web page",
                            HtmlQuestion = "What Does The Html <Audio> Element Do"
                        },
                        new
                        {
                            Id = 6,
                            CodeAnswer = "",
                            HtmlAnswer = "The autoplay attribute starts a video automatically",
                            HtmlQuestion = "What Does The Autoplay Attribute Do To A <Video> Tag"
                        },
                        new
                        {
                            Id = 7,
                            CodeAnswer = "",
                            HtmlAnswer = "The <video> tag is used to embed video content in a document, such as a movie clip or other video streams",
                            HtmlQuestion = "What Does A <Video> Tag Do"
                        },
                        new
                        {
                            Id = 8,
                            CodeAnswer = "",
                            HtmlAnswer = "You get this (®)",
                            HtmlQuestion = "What Character Do You Get When You Use &Reg;"
                        },
                        new
                        {
                            Id = 9,
                            CodeAnswer = "",
                            HtmlAnswer = "You get this (©)",
                            HtmlQuestion = "What Character Do You Get When You Use &Copy;"
                        },
                        new
                        {
                            Id = 10,
                            CodeAnswer = "",
                            HtmlAnswer = "Some characters are reserved in HTML",
                            HtmlQuestion = "What Are Html Entities"
                        },
                        new
                        {
                            Id = 11,
                            CodeAnswer = "",
                            HtmlAnswer = "The <section> tag defines a section in a document",
                            HtmlQuestion = "What Does A <Section> Element Do"
                        },
                        new
                        {
                            Id = 12,
                            CodeAnswer = "",
                            HtmlAnswer = "The <nav> tag defines a set of navigation links",
                            HtmlQuestion = "What Does A <Nav> Element Do"
                        },
                        new
                        {
                            Id = 13,
                            CodeAnswer = "",
                            HtmlAnswer = "The <mark> tag defines text that should be marked or highlighted",
                            HtmlQuestion = "What Does A <Mark> Element Do"
                        },
                        new
                        {
                            Id = 14,
                            CodeAnswer = "",
                            HtmlAnswer = "The <main> tag specifies the main content of a document",
                            HtmlQuestion = "What Does A <Main> Element Do"
                        },
                        new
                        {
                            Id = 15,
                            CodeAnswer = "",
                            HtmlAnswer = "The <header> element represents a container for introductory content or a set of navigational links",
                            HtmlQuestion = "What Does A <Hearder> Element Do"
                        },
                        new
                        {
                            Id = 16,
                            CodeAnswer = "",
                            HtmlAnswer = "<header> <main> <mark> <nav> <section>",
                            HtmlQuestion = "What Are Some Semantic Elements"
                        },
                        new
                        {
                            Id = 17,
                            CodeAnswer = "",
                            HtmlAnswer = "A semantic element clearly describes its meaning to both the browser and the developer",
                            HtmlQuestion = "What Is A Semantic Element"
                        },
                        new
                        {
                            Id = 18,
                            CodeAnswer = "",
                            HtmlAnswer = "The <footer> element defines a footer for a document or section",
                            HtmlQuestion = "What Does The Html <Footer> Element Do"
                        },
                        new
                        {
                            Id = 19,
                            CodeAnswer = "",
                            HtmlAnswer = "The HTML <var> element  is used to define a variable in programming or in a mathematical expression",
                            HtmlQuestion = "What Is Html <Var> Tag Used For"
                        },
                        new
                        {
                            Id = 20,
                            CodeAnswer = "",
                            HtmlAnswer = "The HTML <code> element  is used to define a piece of computer code",
                            HtmlQuestion = "What Is Html <Code> Tag Used For"
                        },
                        new
                        {
                            Id = 21,
                            CodeAnswer = "",
                            HtmlAnswer = "The HTML <samp> element is used to define sample output from a computer program",
                            HtmlQuestion = "What Is Html <Samp> Tag Used For"
                        },
                        new
                        {
                            Id = 22,
                            CodeAnswer = "",
                            HtmlAnswer = "The HTML <kbd> element is used to define keyboard input. The content inside is displayed in the browser's default monospace font",
                            HtmlQuestion = "What Is Html <Kbd> Tag Used For"
                        },
                        new
                        {
                            Id = 23,
                            CodeAnswer = "",
                            HtmlAnswer = "The <meta> element is typically used to specify the character set, page description, keywords, author of the document, and viewport settings",
                            HtmlQuestion = "What Does The Html <Meta> Element Do"
                        },
                        new
                        {
                            Id = 24,
                            CodeAnswer = "",
                            HtmlAnswer = "The <link> element defines the relationship between the current document and an external resource",
                            HtmlQuestion = "What Does The Html <Link> Element Do"
                        },
                        new
                        {
                            Id = 25,
                            CodeAnswer = "",
                            HtmlAnswer = "The HTML <script> tag is used to define a client-side script (JavaScript)",
                            HtmlQuestion = "What Does A <Script> Tag Do"
                        },
                        new
                        {
                            Id = 26,
                            CodeAnswer = "",
                            HtmlAnswer = "The <title> element defines the title of the document. The title must be text-only, and it is shown in the browser's title bar or in the page's tab",
                            HtmlQuestion = "What Does The Html <Title> Element Do"
                        },
                        new
                        {
                            Id = 27,
                            CodeAnswer = "",
                            HtmlAnswer = "The <head> element is a container for metadata (data about data) and is placed between the <html> tag and the <body> tag",
                            HtmlQuestion = "What Does The Html <Head> Element Do"
                        },
                        new
                        {
                            Id = 28,
                            CodeAnswer = "",
                            HtmlAnswer = "A relative file path points to a file relative to the current page",
                            HtmlQuestion = "What Is A Relative File Path"
                        },
                        new
                        {
                            Id = 29,
                            CodeAnswer = "",
                            HtmlAnswer = "An absolute file path is the full URL to a file",
                            HtmlQuestion = "What Is A Absolute File Path"
                        },
                        new
                        {
                            Id = 30,
                            CodeAnswer = "",
                            HtmlAnswer = "A file path describes the location of a file in a web site's folder structure",
                            HtmlQuestion = "What Is A Html File Path"
                        },
                        new
                        {
                            Id = 31,
                            CodeAnswer = "",
                            HtmlAnswer = "An HTML iframe is used to display a web page within a web page",
                            HtmlQuestion = "What Does The Html Iframe Used For"
                        },
                        new
                        {
                            Id = 32,
                            CodeAnswer = "",
                            HtmlAnswer = "no, You cannot have more than one element with the same id in an HTML document",
                            HtmlQuestion = "Can You Use The Same Id On Multiple Html Elements"
                        },
                        new
                        {
                            Id = 33,
                            CodeAnswer = "",
                            HtmlAnswer = "The HTML id attribute is used to specify a unique id for an HTML element",
                            HtmlQuestion = "What Does A Id Attribute Do"
                        },
                        new
                        {
                            Id = 34,
                            CodeAnswer = "",
                            HtmlAnswer = "yes you can use multiple classes on one HTML element",
                            HtmlQuestion = "Can You Use Multiple Classes On One Html Element"
                        },
                        new
                        {
                            Id = 35,
                            CodeAnswer = "",
                            HtmlAnswer = "yes, Multiple HTML elements can share the same class",
                            HtmlQuestion = "Can You Use The Same Class On Multiple Html Elements"
                        },
                        new
                        {
                            Id = 36,
                            CodeAnswer = "",
                            HtmlAnswer = "The HTML class attribute is used to specify a class for an HTML element",
                            HtmlQuestion = "What Does A Class Attribute Do"
                        },
                        new
                        {
                            Id = 37,
                            CodeAnswer = "",
                            HtmlAnswer = "The <span> tag is an inline container used to mark up a part of a text, or a part of a document.",
                            HtmlQuestion = "What Does A <Span> Tag Do"
                        },
                        new
                        {
                            Id = 38,
                            CodeAnswer = "",
                            HtmlAnswer = "The <div> tag is used as a container for HTML elements",
                            HtmlQuestion = "What Is A <Div> Tag Mostly Used For"
                        },
                        new
                        {
                            Id = 39,
                            CodeAnswer = "",
                            HtmlAnswer = "The <div> tag defines a division or a section in an HTML document",
                            HtmlQuestion = "What Does A <Div> Tag Do"
                        },
                        new
                        {
                            Id = 40,
                            CodeAnswer = "",
                            HtmlAnswer = "An inline element does not start on a new line. Also an inline element only takes up as much width as necessary.",
                            HtmlQuestion = "What Does A Inline Element Do"
                        },
                        new
                        {
                            Id = 41,
                            CodeAnswer = "",
                            HtmlAnswer = "A block-level element always starts on a new line. Also a block-level element always takes up the full width available (stretches out to the left and right as far as it can). Also a block level element has a top and a bottom margin",
                            HtmlQuestion = "What Does A Block-Level Element Do"
                        },
                        new
                        {
                            Id = 42,
                            CodeAnswer = "",
                            HtmlAnswer = "Lists can be nested (list inside list)",
                            HtmlQuestion = "Can Lists Be Nested"
                        },
                        new
                        {
                            Id = 43,
                            CodeAnswer = "",
                            HtmlAnswer = "The <dd> tag is used to describe a term/name in a description list",
                            HtmlQuestion = "What Does A <Dd> Tag Do"
                        },
                        new
                        {
                            Id = 44,
                            CodeAnswer = "",
                            HtmlAnswer = "The <dt> tag defines a term/name in a description list",
                            HtmlQuestion = "What Does A <Dt> Tag Do"
                        },
                        new
                        {
                            Id = 45,
                            CodeAnswer = "",
                            HtmlAnswer = "The <dl> tag defines a description list",
                            HtmlQuestion = "What Does A <Dl> Tag Do"
                        },
                        new
                        {
                            Id = 46,
                            CodeAnswer = "",
                            HtmlAnswer = "The <ol> tag defines an ordered list. An ordered list can be numerical or alphabetical",
                            HtmlQuestion = "What Does A <Ol> Tag Do"
                        },
                        new
                        {
                            Id = 47,
                            CodeAnswer = "",
                            HtmlAnswer = "The <li> tag defines a list item",
                            HtmlQuestion = "What Does A <Li> Tag Do"
                        },
                        new
                        {
                            Id = 48,
                            CodeAnswer = "",
                            HtmlAnswer = "The <ul> tag defines an unordered (bulleted) list",
                            HtmlQuestion = "What Does A <Ul> Tag Do"
                        },
                        new
                        {
                            Id = 49,
                            CodeAnswer = "",
                            HtmlAnswer = "The <th> tag defines a header cell in an HTML table",
                            HtmlQuestion = "What Does A <Th> Tag Do"
                        },
                        new
                        {
                            Id = 50,
                            CodeAnswer = "",
                            HtmlAnswer = "The <tr> tag defines a row in an HTML table",
                            HtmlQuestion = "What Does A <Tr> Tag Do"
                        },
                        new
                        {
                            Id = 51,
                            CodeAnswer = "",
                            HtmlAnswer = "The <td> tag defines a standard data cell in an HTML table",
                            HtmlQuestion = "What Does A <Td> Tag Do"
                        },
                        new
                        {
                            Id = 52,
                            CodeAnswer = "",
                            HtmlAnswer = "The <table> tag defines an HTML table",
                            HtmlQuestion = "What Does A <Table> Tag Do"
                        },
                        new
                        {
                            Id = 53,
                            CodeAnswer = "",
                            HtmlAnswer = "<table> <tr> <td> <th>",
                            HtmlQuestion = "What Tags Are Used In A Html Tables"
                        },
                        new
                        {
                            Id = 54,
                            CodeAnswer = "",
                            HtmlAnswer = "_top - Opens the document in the full body of the window",
                            HtmlQuestion = "What Does _Top Do"
                        },
                        new
                        {
                            Id = 55,
                            CodeAnswer = "",
                            HtmlAnswer = "_parent - Opens the document in the parent fram",
                            HtmlQuestion = "What Does _ Parent Do"
                        },
                        new
                        {
                            Id = 56,
                            CodeAnswer = "",
                            HtmlAnswer = "_blank - Opens the document in a new window or tab",
                            HtmlQuestion = "What Does _Blank Do"
                        },
                        new
                        {
                            Id = 57,
                            CodeAnswer = "",
                            HtmlAnswer = "_self - Default. Opens the document in the same window/tab as it was clicked",
                            HtmlQuestion = "What Does  _Self Do"
                        },
                        new
                        {
                            Id = 58,
                            CodeAnswer = "",
                            HtmlAnswer = "_self , _blank , _parent , _top",
                            HtmlQuestion = "What Are The Vaules A Target Attribute Can Have"
                        },
                        new
                        {
                            Id = 59,
                            CodeAnswer = "",
                            HtmlAnswer = "The target attribute specifies where to open the linked document",
                            HtmlQuestion = "What Does The Target Attribute Do To <A> Element"
                        },
                        new
                        {
                            Id = 60,
                            CodeAnswer = "",
                            HtmlAnswer = "the <!-- --> comments anything inside the <!-- kinda like this --> that will not display that text in the ui",
                            HtmlQuestion = "What Does A <!-- -->  Element Do"
                        },
                        new
                        {
                            Id = 61,
                            CodeAnswer = "",
                            HtmlAnswer = "the <abbr> tag defines an abbreviation or an acronym, like HTML, CSS, Mr., Dr., ASAP, ATM",
                            HtmlQuestion = "What Does A <Abbr> Element Do"
                        },
                        new
                        {
                            Id = 62,
                            CodeAnswer = "",
                            HtmlAnswer = "the <q> tag defines a short quotation",
                            HtmlQuestion = "What Does A <Q> Element Do"
                        },
                        new
                        {
                            Id = 63,
                            CodeAnswer = "",
                            HtmlAnswer = "the <blockquote> element defines a section that is quoted from another source",
                            HtmlQuestion = "What Does A <Blockquote> Element Do"
                        },
                        new
                        {
                            Id = 64,
                            CodeAnswer = "",
                            HtmlAnswer = "The <i> element makes text Italic",
                            HtmlQuestion = "What Does A <I> Element Do"
                        },
                        new
                        {
                            Id = 65,
                            CodeAnswer = "",
                            HtmlAnswer = "the <b> element makes text Bold",
                            HtmlQuestion = "What Does A <B> Element Do"
                        },
                        new
                        {
                            Id = 66,
                            CodeAnswer = "",
                            HtmlAnswer = "the <pre> element defines preformatted text",
                            HtmlQuestion = "What Does A <Pre> Element Do"
                        },
                        new
                        {
                            Id = 67,
                            CodeAnswer = "",
                            HtmlAnswer = "The title attribute defines some extra information about an element",
                            HtmlQuestion = "What Does A Title Attribute Do"
                        },
                        new
                        {
                            Id = 68,
                            CodeAnswer = "",
                            HtmlAnswer = "You should always include the lang attribute inside the <html> tag, to declare the language of the Web page. This is meant to assist search engines and browsers",
                            HtmlQuestion = "What Does A Lang Attribute Do"
                        },
                        new
                        {
                            Id = 69,
                            CodeAnswer = "",
                            HtmlAnswer = "The style attribute is used to add styles to an element, such as color, font, size, and more",
                            HtmlQuestion = "What Does A Style Attribute Do"
                        },
                        new
                        {
                            Id = 70,
                            CodeAnswer = "",
                            HtmlAnswer = "you want to use it if the image for some reason cannot be displayed. This can be due to slow connection, or an error in the src attribute, or if the user uses a screen reader",
                            HtmlQuestion = "Why Would You Use A Alt Attribute"
                        },
                        new
                        {
                            Id = 71,
                            CodeAnswer = "",
                            HtmlAnswer = "specifies an alternate text for an image",
                            HtmlQuestion = "What Does A Alt Attribute Do To A <Img>"
                        },
                        new
                        {
                            Id = 72,
                            CodeAnswer = "",
                            HtmlAnswer = "specifies the height of a image in pixels",
                            HtmlQuestion = "What Does A Height Attribute Do To A <Img>"
                        },
                        new
                        {
                            Id = 73,
                            CodeAnswer = "",
                            HtmlAnswer = "specifies the width of a image in pixels",
                            HtmlQuestion = "What Does A Width Attribute Do To A <Img>"
                        },
                        new
                        {
                            Id = 74,
                            CodeAnswer = "",
                            HtmlAnswer = "The src attribute specifies the path to the image to be displayed",
                            HtmlQuestion = "What Does A Src Attribute Do To A <Img>"
                        },
                        new
                        {
                            Id = 75,
                            CodeAnswer = "",
                            HtmlAnswer = "The <img> tag is used to embed an image in an HTML page",
                            HtmlQuestion = "What Does A <Img> Element Do"
                        },
                        new
                        {
                            Id = 76,
                            CodeAnswer = "",
                            HtmlAnswer = "The href attribute specifies the URL of the page the link goes to on <a> tag",
                            HtmlQuestion = "What Does A Href Attribute Do"
                        },
                        new
                        {
                            Id = 77,
                            CodeAnswer = "",
                            HtmlAnswer = "HTML attributes provide additional information about HTML elements",
                            HtmlQuestion = "What Is A Html Attribute"
                        },
                        new
                        {
                            Id = 78,
                            CodeAnswer = "",
                            HtmlAnswer = "The <a> element defines a HTML link",
                            HtmlQuestion = "What Does A <A> Element Do"
                        },
                        new
                        {
                            Id = 79,
                            CodeAnswer = "",
                            HtmlAnswer = "The <hr/> element produces a line and spacing under the previous element",
                            HtmlQuestion = "What Does A <Hr/> Element Do"
                        },
                        new
                        {
                            Id = 80,
                            CodeAnswer = "",
                            HtmlAnswer = "some HTML elements have no content (like the <br/> element), Empty elements do not have an end tag!",
                            HtmlQuestion = "What Is A Empty Element"
                        },
                        new
                        {
                            Id = 81,
                            CodeAnswer = "",
                            HtmlAnswer = "The <br/> element produces a line break in text",
                            HtmlQuestion = "What Does The <Br/> Element Do"
                        },
                        new
                        {
                            Id = 82,
                            CodeAnswer = "",
                            HtmlAnswer = "The <p> element defines a paragraph",
                            HtmlQuestion = "What Does The <P> Element Do"
                        },
                        new
                        {
                            Id = 83,
                            CodeAnswer = "",
                            HtmlAnswer = "There are 6 heading, the 6 headings are <h1> - <h6>",
                            HtmlQuestion = "How Many Heading Elements Are There"
                        },
                        new
                        {
                            Id = 84,
                            CodeAnswer = "",
                            HtmlAnswer = "The <h1> <h2> <h3> <h4> <h5> <h6> elements defines a heading, the lower the numbr the bigger the heading",
                            HtmlQuestion = "What Does The <H1> <H2> <H3> <H4> <H5> <H6> Elements Do"
                        },
                        new
                        {
                            Id = 85,
                            CodeAnswer = "",
                            HtmlAnswer = "The <body> element defines the document's body, and is a container for all the visible contents, such as headings, paragraphs, images, hyperlinks, tables, lists, etc",
                            HtmlQuestion = "What Does The <Body> Element Do"
                        },
                        new
                        {
                            Id = 86,
                            CodeAnswer = "",
                            HtmlAnswer = "The <title> element specifies a title for the HTML page (which is shown in the browser's title bar or in the page's tab)",
                            HtmlQuestion = "What Does The <Title> Element Do"
                        },
                        new
                        {
                            Id = 87,
                            CodeAnswer = "",
                            HtmlAnswer = "The <head> element contains meta information about the HTML page",
                            HtmlQuestion = "What Does The <Head> Element Do"
                        },
                        new
                        {
                            Id = 88,
                            CodeAnswer = "",
                            HtmlAnswer = "The <html> element is the root element of an HTML page",
                            HtmlQuestion = "What Does The <Html> Element Do"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
